name: login
description: Projet fin de module Flutter.




version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  flutter_secure_storage: ^5.0.2

  local_auth: ^1.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.1


flutter:


  uses-material-design: true


